### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by lierdakil** [AtomLinterPlus/linter-plus#5]
[Enter steps to reproduce below:]

This error pops up when I focus preview panes (i.e. active pane item is not an editor)

**Atom Version**: 0.209.0-d965eb7
**System**: "Gentoo Base
**Thrown From**: [linter-plus](https://github.com/AtomLinterPlus/linter-plus) package, v0.4.1

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/livid/.atom/packages/linter-plus/lib/linter-view.coffee:21

TypeError: undefined is not a function
  at LinterView.render (/home/livid/.atom/packages/linter-plus/lib/linter-view.coffee:21:48)
  at /home/livid/.atom/packages/linter-plus/lib/linter-plus.coffee:33:13
  at Emitter.module.exports.Emitter.emit (/home/livid/bin/atom-dir/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /home/livid/bin/atom-dir/share/atom/resources/app.asar/src/pane-container.js:343:34
  at Pane.module.exports.Pane.observeActiveItem (/home/livid/bin/atom-dir/share/atom/resources/app.asar/src/pane.js:182:7)
  at /home/livid/bin/atom-dir/share/atom/resources/app.asar/src/pane-container.js:342:42
  at Emitter.module.exports.Emitter.emit (/home/livid/bin/atom-dir/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.setActivePane (/home/livid/bin/atom-dir/share/atom/resources/app.asar/src/pane-container.js:218:22)
  at Pane.module.exports.Pane.activate (/home/livid/bin/atom-dir/share/atom/resources/app.asar/src/pane.js:607:15)
  at Pane.module.exports.Pane.focus (/home/livid/bin/atom-dir/share/atom/resources/app.asar/src/pane.js:193:21)
  at atom-pane.<anonymous> (/home/livid/bin/atom-dir/share/atom/resources/app.asar/src/pane-element.js:59:23)

```

### Commands

```
     -2:46.7.0 core:delete (atom-text-editor.editor.is-focused)
     -2:44.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:43.4.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -2:42.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:42.1.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
  8x -2:38.9.0 core:select-right (atom-text-editor.editor.is-focused)
     -2:36.7.0 core:delete (atom-text-editor.editor.is-focused)
  4x -2:35.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:34.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
 12x -2:28.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:26.9.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
  2x -2:26.6.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -2:26 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -2:21.4.0 core:save (atom-text-editor.editor.is-focused)
     -2:20.6.0 markdown-preview-pandoc:toggle (atom-text-editor.editor.is-focused)
  4x -1:07.9.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-lint",
      "haskell-hindent",
      "markdown-preview-plus",
      "markdown-preview",
      "autocomplete",
      "terminal-status",
      "linter-hlint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.4.4
autocomplete-paths, v1.0.2
autocomplete-plus-python-jedi, v0.3.6
build, v0.38.0
haskell-ghc-mod, v0.7.8
haskell-pointfree, v0.1.2
ide-haskell, v0.5.13
language-dot, v1.6.0
language-haskell, v1.1.4
language-latex, v0.6.1
linter, v0.12.7
linter-coffeelint, v0.3.2
linter-plus, v0.4.1
linter-pylint, v0.2.2
markdown-preview-pandoc, v0.0.14
markdown-table-formatter, v2.5.1
terminal-panel, v1.14.1
zotero-bibtex-autocomplete, v0.0.0

# Dev
autocomplete-plus, v2.3.0
```

**Comment by steelbrain** [comment]
While a fix has been pushed, It's still unrecommended to use this repo unless one of your package is depending on it, You're supposed to clone the other linter-plus repo or wait for the release.

**Comment by lierdakil** [comment]
I don't "use" it necessarily, I just installed it for a quick and dirty test :)
