### ISSUE TITLE
Failed to activate the linter-plus package

### ISSUE THREAD

**Issue by poyhsiao** [AtomLinterPlus/linter-plus#8]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.211.0-1a3441a
**System**: Mac OS X 10.10.4
**Thrown From**: [linter-plus](https://github.com/AtomLinterPlus/linter-plus) package, v0.5.0

### Stack Trace

Failed to activate the linter-plus package

```
At Failed to execute 'registerElement' on 'Document': Registration failed for type 'linter-bottom-tab'. A type with that name is already registered.

Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'linter-bottom-tab'. A type with that name is already registered.
    at Error (native)
    at Object.<anonymous> (/Users/kimhsiao/.atom/packages/linter-plus/lib/views/bottom-tab.js:31:39)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/kimhsiao/.atom/packages/linter-plus/lib/linter-views.coffee:4:15)
    at Object.<anonymous> (/Users/kimhsiao/.atom/packages/linter-plus/lib/linter-views.coffee:230:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/kimhsiao/.atom/packages/linter-plus/lib/linter-plus.coffee:8:17)
    at Object.<anonymous> (/Users/kimhsiao/.atom/packages/linter-plus/lib/linter-plus.coffee:96:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.module.exports.activate (/Users/kimhsiao/.atom/packages/linter-plus/lib/main.coffee:23:35)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:436:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:431:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:412:46)
    at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:641:21)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:95:23)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:36:7)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-compile-coffee",
      "ask-stack",
      "minimap",
      "atomtools",
      "css-color-highlight",
      "cloud-sync",
      "cloud-sync",
      "cloud-sync",
      "language-jsx",
      "open-on-search-engine",
      "cloud-sync",
      "language-jsx"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
auto-update-packages, v1.0.0
autoclose-html, v0.18.0
autocomplete-paths, v1.0.2
color-picker, v2.0.7
docblockr, v0.7.2
editor-stats, v0.17.0
editorconfig, v1.0.0
file-icons, v1.5.7
hex, v0.6.2
language-cjsx, v0.3.0
language-jade, v0.4.0
linter, v1.0.0
linter-coffeelint, v0.3.2
linter-csslint, v0.0.13
linter-htmlhint, v0.0.16
linter-js-yaml, v1.0.1
linter-jshint, v0.1.6
linter-jsxhint, v0.1.2
linter-php, v0.0.15
linter-plus, v0.5.0
linter-shellcheck, v0.0.8
markdown-format, v2.5.1
minimap-git-diff, v4.1.3
minimap-highlight-selected, vundefined
nuclide-installer, v0.0.21
open-recent, v2.2.4
react, v0.12.0
terminal-status, v1.6.8
web-browser, v1.5.0

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
Please note that `linter-plus` is only for legacy purposes, You are advised to use `linter` instead, because the codebase has basically merged into it.
